
name: dockertest

services:

  mongodb:
    build: ./mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  simplenodejs: 
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/:/app
    ports: 
      - 9003:9003

  nodejs:
    build: ../backend
    restart: unless-stopped
    ports:
      - 9002:9002
    volumes:
      - ../backend/:/app
      - /app/node_modules
  nginx:
    # image: bewe-nginx
    depends_on:
      - nodejs
    build: ./nginx/
    restart: unless-stopped
    # env_file: ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 80:80

volumes:
    db:
  # app:
  #   depends_on:
  #     - mongodb
  #   build: ./bezkoder-app
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_USER=$MONGODB_USER
  #     - DB_PASSWORD=$MONGODB_PASSWORD
  #     - DB_NAME=$MONGODB_DATABASE
  #     - DB_PORT=$MONGODB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true

# volumes:
#   db:
