
# name: bewecore

# services:

#   # redis:
#   #   image: "redis"
#   #   ports:
#   #     - 6379:6379
#   #   restart: unless-stopped
#   #   environment:
#   #     - REDIS_PASSWORD=beweredis
#   #   healthcheck:
#   #     test: ["CMD", "redis-cli", "ping"]
#   #   networks:
#   #     - bewe-network

#   # mongodb:
#   #   build: ./mongodb
#   #   restart: unless-stopped
#   #   ports:
#   #     - 27017:27017
#   #   volumes:
#   #     - /data/bewe-db:/data/db
#   #   networks:
#   #     - bewe-network

#   nginx:
#     build: ./nginx/
#     restart: unless-stopped
#     container_name: bewe-nginx
#     depends_on:
#       - backend
#     # env_file: ./.env
#     # environment:
#     #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
#     #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
#     ports:
#       - 80:80
#     extra_hosts:
#       - host.docker.internal:host-gateway
#     networks:
#       - bewe-network

#   # nodejs:
#   #   build: ../backend
#   #   restart: unless-stopped
#   #   depends_on:
#   #     - mongodb
#   #   ports:
#   #     - 9002:9002
#   #   volumes:
#   #     - ../backend/:/app
#   #     - /app/node_modules
#   #   command: "npm run dev"
#   #   extra_hosts:
#   #     - host.docker.internal:host-gateway
#   #   networks:
#   #     - bewe-network
# networks:
#   bewe-network:
#     external: true
#   # simplenodejs:
#   #   build: ./api
#   #   restart: unless-stopped
#   #   volumes:
#   #     - ./api/:/app
#   #     - /app/node_modules
#   #   ports:
#   #     - 9003:9003

# # volumes:
# #     db:
#   # app:
#   #   depends_on:
#   #     - mongodb
#   #   build: ./bezkoder-app
#   #   restart: unless-stopped
#   #   env_file: ./.env
#   #   ports:
#   #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#   #   environment:
#   #     - DB_HOST=mongodb
#   #     - DB_USER=$MONGODB_USER
#   #     - DB_PASSWORD=$MONGODB_PASSWORD
#   #     - DB_NAME=$MONGODB_DATABASE
#   #     - DB_PORT=$MONGODB_DOCKER_PORT
#   #   stdin_open: true
#   #   tty: true

# # volumes:
# #   db:
