
name: bewe-services

services:

  backend-copy:
    build: ../../../backend-copy/
    restart: unless-stopped
    container_name: bw-backend-copy
    ports:
      - 9003:9003
    volumes:
      - ../../../backend-copy/:/app/
      - /app/node_modules
    command: "npm run dev"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - bewe-network

networks:
  bewe-network:
    external: true