#!/bin/bash
mongoimport --db bh --collection agreements agreements.json
mongoimport --db bh --collection apps apps.json
mongoimport --db bh --collection assets assets.json
mongoimport --db bh --collection bhaccountagreements bhaccountagreements.json
mongoimport --db bh --collection bhaccountbillconfigs bhaccountbillconfigs.json
mongoimport --db bh --collection bhaccountclientgateways bhaccountclientgateways.json
mongoimport --db bh --collection bhaccountbillconfigs bhaccountbillconfigs.json
mongoimport --db bh --collection bhaccountintegrations bhaccountintegrations.json
mongoimport --db bh --collection bhaccountdashboards bhaccountdashboards.json
mongoimport --db bh --collection bhaccountintegrationcollections bhaccountintegrationcollections.json
mongoimport --db bh --collection marketingrules marketingrules.json
mongoimport --db bh --collection marketingrulelogs marketingrulelogs.json
mongoimport --db bh --collection bhaccountextendeds bhaccountextendeds.json
mongoimport --db bh --collection bhaccountreports bhaccountreports.json
mongoimport --db bh --collection bhaccounts bhaccounts.json
mongoimport --db bh --collection bhaccountsubscriptions bhaccountsubscriptions.json
mongoimport --db bh --collection bhbills bhbills.json
mongoimport --db bh --collection bhcategories bhcategories.json
mongoimport --db bh --collection bookingbills bookingbills.json
mongoimport --db bh --collection bookingpayments bookingpayments.json
mongoimport --db bh --collection budgetbases budgetbases.json
mongoimport --db bh --collection budgets budgets.json
mongoimport --db bh --collection campaigns campaigns.json
mongoimport --db bh --collection cashes cashes.json
mongoimport --db bh --collection cashmoneys cashmoneys.json
mongoimport --db bh --collection clientcourses clientcourses.json
mongoimport --db bh --collection clienteventclasses clienteventclasses.json
mongoimport --db bh --collection clientcreditcards clientcreditcards.json
mongoimport --db bh --collection clientdiscounts clientdiscounts.json
mongoimport --db bh --collection clientdocuments clientdocuments.json
mongoimport --db bh --collection clientnotes clientnotes.json
mongoimport --db bh --collection clients clients.json
mongoimport --db bh --collection clientsubscriptions clientsubscriptions.json
mongoimport --db bh --collection clienttrackings clienttrackings.json
mongoimport --db bh --collection commerces commerces.json
mongoimport --db bh --collection consents consents.json
mongoimport --db bh --collection countries countries.json
mongoimport --db bh --collection creditcards creditcards.json
mongoimport --db bh --collection creditcardtransactions creditcardtransactions.json
mongoimport --db bh --collection datemodremovals datemodremovals.json
mongoimport --db bh --collection datemods datemods.json
mongoimport --db bh --collection daynotes daynotes.json
mongoimport --db bh --collection demoids demoids.json
mongoimport --db bh --collection discounts discounts.json
mongoimport --db bh --collection documenttemplates documenttemplates.json
mongoimport --db bh --collection employeelogs employeelogs.json
mongoimport --db bh --collection employeeproducts employeeproducts.json
mongoimport --db bh --collection employees employees.json
mongoimport --db bh --collection estimatebases estimatebases.json
mongoimport --db bh --collection estimates estimates.json
mongoimport --db bh --collection eventclasses eventclasses.json
mongoimport --db bh --collection expenseperiodics expenseperiodics.json
mongoimport --db bh --collection expenseelectronics expenseelectronics.json
mongoimport --db bh --collection expenses expenses.json
mongoimport --db bh --collection giftcards giftcards.json
mongoimport --db bh --collection insurances insurances.json
mongoimport --db bh --collection itemtransactions itemtransactions.json
mongoimport --db bh --collection orders orders.json
mongoimport --db bh --collection polls polls.json
mongoimport --db bh --collection products products.json
mongoimport --db bh --collection productorders productorders.json
mongoimport --db bh --collection productstocklogs productstocklogs.json
mongoimport --db bh --collection pulltemplates pulltemplates.json
mongoimport --db bh --collection reports reports.json
mongoimport --db bh --collection reportviews reportviews.json
mongoimport --db bh --collection resources resources.json
mongoimport --db bh --collection sendings sendings.json
mongoimport --db bh --collection statsclients statsclients.json
mongoimport --db bh --collection statsevents statsevents.json
mongoimport --db bh --collection statsproducts statsproducts.json
mongoimport --db bh --collection statstreatments statstreatments.json
mongoimport --db bh --collection storeorders storeorders.json
mongoimport --db bh --collection storeproducts storeproducts.json
mongoimport --db bh --collection subscriptions subscriptions.json
mongoimport --db bh --collection ticketelectronics ticketelectronics.json
mongoimport --db bh --collection ticketonholds ticketonholds.json
mongoimport --db bh --collection tickets tickets.json
mongoimport --db bh --collection ticketviews ticketviews.json
mongoimport --db bh --collection timetables timetables.json
mongoimport --db bh --collection treatments treatments.json
mongoimport --db bh --collection treatmentbookings treatmentbookings.json
mongoimport --db bh --collection treatmentphotos treatmentphotos.json
mongoimport --db bh --collection tvs tvs.json
mongoimport --db bh --collection tvactivities tvactivities.json
mongoimport --db bh --collection webs webs.json
mongoimport --db bh --collection webtemplates webtemplates.json
mongoimport --db bh --collection workbusies workbusies.json
mongoimport --db bh --collection worklogs worklogs.json
mongoimport --db bh --collection works works.json
mongoimport --db bh --collection messagesendingsevents messagesendingsevents.json
mongoimport --db bh --collection messagesendings messagesendings.json
mongoimport --db bh --collection addons addons.json
mongoimport --db bh --collection addonlogs addonlogs.json