name: bewe-services

services:
  bewe-api:
    restart: unless-stopped
    build: ${HOME}/bewe/linda/
    container_name: bw-linda
    command: npm run dev
    volumes:
      - ${HOME}/bewe/linda/:/app/
      - /app/node_modules
    ports:
      - 9010:9010
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - bewe-network

networks:
  bewe-network:
    external: true